"""initial schema

Revision ID: e3f914dda3f6
Revises: 
Create Date: 2026-09-30 00:57:50.688823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f914dda3f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('color_hue', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('data_note', sa.String(length=300), nullable=True),
    sa.Column('uses_demo_data', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_name'), ['name'], unique=False)

    op.create_table('text_embeddings',
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('text_hash', 'model')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'owner', 'admin', name='role', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.Column('home_label', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'owner', 'admin')", name='role'),
    sa.CheckConstraint("role IN ('customer', 'owner', 'admin')", name='role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('typical_price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_items_subcategory'), ['subcategory'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedents', sa.JSON(), nullable=False),
    sa.Column('consequents', sa.JSON(), nullable=False),
    sa.Column('antecedent_key', sa.String(length=120), nullable=False),
    sa.Column('support', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lift', sa.Float(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_antecedent_key'), ['antecedent_key'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('normalized_query', sa.String(length=200), nullable=False),
    sa.Column('category_slug', sa.String(length=60), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_user_id'), ['user_id'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('opening_hours', sa.String(length=80), nullable=True),
    sa.Column('closed_on', sa.String(length=40), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('offers_pickup', sa.Boolean(), nullable=False),
    sa.Column('offers_delivery', sa.Boolean(), nullable=False),
    sa.Column('delivery_radius_km', sa.Float(), nullable=False),
    sa.Column('delivery_fee', sa.Float(), nullable=False),
    sa.Column('free_delivery_above', sa.Float(), nullable=True),
    sa.Column('hold_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('inventory_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('delivery_radius_km >= 0', name='ck_shop_radius'),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name='ck_shop_lat'),
    sa.CheckConstraint('lng BETWEEN -180 AND 180', name='ck_shop_lng'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index('ix_shops_lat_lng', ['lat', 'lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_locality'), ['locality'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_owner_id'), ['owner_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SHOP_CONFIRMED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'DELIVERY_FAILED', 'RETURNED_TO_SHOP', name='orderstatus', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=300), nullable=False),
    sa.Column('delivery_lat', sa.Float(), nullable=False),
    sa.Column('delivery_lng', sa.Float(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('delivery_fee', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('stock_held', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'SHOP_CONFIRMED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'DELIVERY_FAILED', 'RETURNED_TO_SHOP')", name='orderstatus'),
    sa.CheckConstraint("status IN ('PENDING', 'SHOP_CONFIRMED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'DELIVERY_FAILED', 'RETURNED_TO_SHOP')", name='orderstatus'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('ix_orders_shop_status', ['shop_id', 'status'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stock_updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_product_price'),
    sa.CheckConstraint('quantity >= 0', name='ck_product_qty'),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'catalog_item_id', name='uq_product_shop_catalog')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_catalog_item_id'), ['catalog_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_price'), ['price'], unique=False)
        batch_op.create_index('ix_products_shop_active', ['shop_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_shop_id'), ['shop_id'], unique=False)

    op.create_table('shop_categories',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id', 'category_id')
    )
    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_status_events_entity', ['entity', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_events_shop_id'), ['shop_id'], unique=False)

    op.create_table('demand_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('predicted_7d', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('days_to_stockout', sa.Float(), nullable=True),
    sa.Column('recommended_restock', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('history_days', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    with op.batch_alter_table('demand_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_forecasts_shop_id'), ['shop_id'], unique=False)

    op.create_table('inventory_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('initial', 'restock', 'adjustment', 'reservation_hold', 'reservation_release', 'order_hold', 'order_release', name='inventoryreason', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("reason IN ('initial', 'restock', 'adjustment', 'reservation_hold', 'reservation_release', 'order_hold', 'order_release')", name='inventoryreason'),
    sa.CheckConstraint("reason IN ('initial', 'restock', 'adjustment', 'reservation_hold', 'reservation_release', 'order_hold', 'order_release')", name='inventoryreason'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_events_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_events_shop_id'), ['shop_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_qty'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('price_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('peer_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewed', 'dismissed', name='anomalystatus', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('review_note', sa.String(length=300), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'reviewed', 'dismissed')", name='anomalystatus'),
    sa.CheckConstraint("status IN ('open', 'reviewed', 'dismissed')", name='anomalystatus'),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_anomalies_catalog_item_id'), ['catalog_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_anomalies_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_anomalies_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_anomalies_status'), ['status'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'READY_FOR_PICKUP', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='reservationstatus', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('hold_minutes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('stock_held', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED', 'CONFIRMED', 'READY_FOR_PICKUP', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED')", name='reservationstatus'),
    sa.CheckConstraint("status IN ('REQUESTED', 'CONFIRMED', 'READY_FOR_PICKUP', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED')", name='reservationstatus'),
    sa.CheckConstraint('quantity > 0', name='ck_reservation_qty'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_reservations_customer_status', ['customer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('ix_reservations_shop_status', ['shop_id', 'status'], unique=False)

    op.create_table('sales_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('basket_id', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('reservation', 'order', 'demo', name='salesource', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('reservation', 'order', 'demo')", name='salesource'),
    sa.CheckConstraint("source IN ('reservation', 'order', 'demo')", name='salesource'),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_history_basket_id'), ['basket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_history_catalog_item_id'), ['catalog_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_history_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_history_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_history_sold_at'), ['sold_at'], unique=False)
        batch_op.create_index('ix_sales_product_date', ['product_id', 'sold_at'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('accuracy_rating', sa.Integer(), nullable=True),
    sa.Column('delivery_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(reservation_id IS NOT NULL) <> (order_id IS NOT NULL)', name='ck_review_source'),
    sa.CheckConstraint('accuracy_rating IS NULL OR accuracy_rating BETWEEN 1 AND 5', name='ck_review_accuracy'),
    sa.CheckConstraint('delivery_rating IS NULL OR delivery_rating BETWEEN 1 AND 5', name='ck_review_delivery'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_review_rating'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('reservation_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_shop_id'), ['shop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_shop_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_customer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))

    op.drop_table('reviews')
    with op.batch_alter_table('sales_history', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_product_date')
        batch_op.drop_index(batch_op.f('ix_sales_history_sold_at'))
        batch_op.drop_index(batch_op.f('ix_sales_history_shop_id'))
        batch_op.drop_index(batch_op.f('ix_sales_history_is_demo'))
        batch_op.drop_index(batch_op.f('ix_sales_history_catalog_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_history_basket_id'))

    op.drop_table('sales_history')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_reservations_shop_status')
        batch_op.drop_index(batch_op.f('ix_reservations_shop_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_product_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_expires_at'))
        batch_op.drop_index('ix_reservations_customer_status')
        batch_op.drop_index(batch_op.f('ix_reservations_customer_id'))

    op.drop_table('reservations')
    with op.batch_alter_table('price_anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_anomalies_status'))
        batch_op.drop_index(batch_op.f('ix_price_anomalies_shop_id'))
        batch_op.drop_index(batch_op.f('ix_price_anomalies_product_id'))
        batch_op.drop_index(batch_op.f('ix_price_anomalies_catalog_item_id'))

    op.drop_table('price_anomalies')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('inventory_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_events_shop_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_events_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_events_created_at'))

    op.drop_table('inventory_events')
    with op.batch_alter_table('demand_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_forecasts_shop_id'))

    op.drop_table('demand_forecasts')
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_events_shop_id'))
        batch_op.drop_index('ix_status_events_entity')
        batch_op.drop_index(batch_op.f('ix_status_events_created_at'))

    op.drop_table('status_events')
    op.drop_table('shop_categories')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_shop_id'))
        batch_op.drop_index('ix_products_shop_active')
        batch_op.drop_index(batch_op.f('ix_products_price'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_catalog_item_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_shop_status')
        batch_op.drop_index(batch_op.f('ix_orders_shop_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_owner_id'))
        batch_op.drop_index(batch_op.f('ix_shops_locality'))
        batch_op.drop_index('ix_shops_lat_lng')

    op.drop_table('shops')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_history_normalized_query'))
        batch_op.drop_index(batch_op.f('ix_search_history_created_at'))

    op.drop_table('search_history')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_antecedent_key'))

    op.drop_table('recommendations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_items_subcategory'))
        batch_op.drop_index(batch_op.f('ix_catalog_items_category_id'))

    op.drop_table('catalog_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('text_embeddings')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_name'))
        batch_op.drop_index(batch_op.f('ix_model_runs_created_at'))

    op.drop_table('model_runs')
    op.drop_table('categories')
    # ### end Alembic commands ###
